timeout: 28800s
steps:
- name: gcr.io/cloud-builders/git
  dir: /workspace/shared-workspace/build
  entrypoint: git
  args:
  - clone
  - '${_SOURCE_URL}'
  - oss-fuzz
- name: gcr.io/cloud-builders/gsutil
  dir: /workspace/shared-workspace/build
  entrypoint: /bin/bash
  args:
  - -c
  - 'gsutil -m cp -r gs://${_GCS_BUCKET}/${_PACKAGE_NAME}/${_FTG_RUNID}/compilable_fuzzers . && mkdir -p ${_OSS_FUZZ_PROJECT_NAME}/aoss_artifacts && mv compilable_fuzzers/* ${_OSS_FUZZ_PROJECT_NAME}/'
- name: gcr.io/cloud-builders/gsutil
  dir: /workspace/shared-workspace/build/org.slf4j_slf4j-api/aoss_artifacts
  entrypoint: /bin/bash
  args:
  - -c
  - 'curl -X GET -H "Authorization: Bearer $(gcloud auth print-access-token)" --output ${_ARTIFACT_ID}-${_VERSION}.jar  "${_AOSS_JAR_DOWNLOAD_URL}"'
- name: gcr.io/cloud-builders/gsutil
  dir: /workspace/shared-workspace/build/org.slf4j_slf4j-api/aoss_artifacts
  entrypoint: /bin/bash
  args:
  - -c
  - 'curl -X GET -H "Authorization: Bearer $(gcloud auth print-access-token)" --output ${_ARTIFACT_ID}-${_VERSION}.pom  "${_AOSS_POM_DOWNLOAD_URL}" && mv ${_ARTIFACT_ID}-${_VERSION}.pom pom.xml'
- name: gcr.io/cloud-builders/gsutil
  dir: /workspace/shared-workspace/build/org.slf4j_slf4j-api/aoss_artifacts
  entrypoint: /bin/bash
  args:
  - -c
  - 'gsutil -m cp -r gs://${_GCS_BUCKET}/${_PACKAGE_NAME}/${_FTG_RUNID}/${_MAVEN_SETTINGS_XML_SUBPATH} .'
- name: gcr.io/cloud-builders/gsutil
  dir: /workspace/shared-workspace/build/org.slf4j_slf4j-api/aoss_artifacts
  entrypoint: /bin/bash
  args:
  - -c
  - 'mkdir .mvn && gsutil -m cp -r gs://${_GCS_BUCKET}/${_PACKAGE_NAME}/${_FTG_RUNID}/${_MAVEN_EXTENSIONS_XML_SUBPATH} . && mv extensions.xml .mvn/'
options:
  logging: CLOUD_LOGGING_ONLY
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
substitutions:
  _PACKAGE_NAME: "org.slf4j:slf4j-api"
  _SOURCE_URL: "https://github.com/google/oss-fuzz.git"
  _OSS_FUZZ_PROJECT_NAME: "org.slf4j_slf4j-api"
  _FUZZING_DURATION: "20s"
  _GCS_BUCKET: "javafuzztestgeneration"
  _FTG_RUNID: "34d00275-959a-4458-8fb6-8f3c26e92ba7"
  _RUN_FUZZERS_SCRIPT_SUBPATH: "gcb_build_scripts/runfuzztests/e205ca7c-da9d-4dc9-a712-96bd3b0bc3d3/run_fuzzers.sh"
  _MAVEN_EXTENSIONS_XML_SUBPATH: "gcb_build_scripts/runfuzztests/e205ca7c-da9d-4dc9-a712-96bd3b0bc3d3/extensions.xml"
  _MAVEN_SETTINGS_XML_SUBPATH: "gcb_build_scripts/runfuzztests/e205ca7c-da9d-4dc9-a712-96bd3b0bc3d3/settings.xml"
  _AOSS_JAR_DOWNLOAD_URL: "https://artifactregistry.googleapis.com/download/v1/projects/cloud-aoss/locations/us/repositories/cloud-aoss-java/files/org%2Fslf4j%2Fslf4j-api%2F2.0.11%2Fslf4j-api-2.0.11.jar:download?alt=media"
  _AOSS_POM_DOWNLOAD_URL: "https://artifactregistry.googleapis.com/download/v1/projects/cloud-aoss/locations/us/repositories/cloud-aoss-java/files/org%2Fslf4j%2Fslf4j-api%2F2.0.11%2Fslf4j-api-2.0.11.pom:download?alt=media"
  _ARTIFACT_ID: "slf4j-api"
  _VERSION: "2.0.11"
  _FUZZER_LIST: "Fuzzer1,Fuzzer3,Fuzzer10"
